### ISSUE TITLE
车道线检测算法调研

### ISSUE THREAD

**Issue by baidut** [baidut/ITS#18]
Lane detection 基本找不到项目，用Road detection language:C++ 在github上有9个，而bitbucket、codeproject、codeplex、sourceforge都没有找到合适的
国内codeforge有车道检测的matlab源码，不过价值不高

**Comment by baidut** [comment]
[使用OpenCV完成车道线检测功能](http://blog.csdn.net/u012201326/article/details/43937035)

项目要求： 
1. 基础部分：完成对车道线视频的车道线识别。随着视频的播放，能实时显示出车道
线（在反透视变换图中显示；如果能投影回原图上，加分），可以用红线描出。车道线越精确，项目质量越好。 

2. 拓展部分： 
1) 反透视变换：根据车道线的图像，计算出反透视变换到鸟瞰图的变换矩阵。 2) 车道线预测：根据前N帧的车道线位置，使用卡尔曼滤波等预测器预测出下
一帧车道线的位置。随着视频的播放，能用不同颜色标出实际的车道线和你的算法预测出的车道线位置。 
3) 直线检测：采用beamlet或其他非霍夫直线检测的方法检测出车道线。

**Comment by baidut** [comment]
[基于opencv的道路车道线检测](http://download.csdn.net/detail/u012767067/6834215)
    采用了边缘检测法先检测出绘图图像的边缘，再hough直线拟合，拟合出图中的直线。由于这样查找到的直线非常多，所以先筛选掉角度明显有误的直线，在剩下的直线中保留最长的一组。
    然后根据栅格扫描的方式进行逐行扫秒，把得到的交点，和道路中间的灰度小块进行块匹配，因为道路的分道线和道路的颜色是不一样的，根据块匹配区分该点是在分道线上还是在道路上，统计得到中心点左右两侧最匹配的两条直线，作为检测到的道路车道线。

基于OpenCV的计算机视觉技术实现/陈胜勇, 刘盛等编著

**Comment by baidut** [comment]
LaneDetection/main.cpp https://github.com/yashchandak/LaneDetection/blob/master/main.cpp 
通过opencv的findContours检测边缘区域，对找到的区域筛选：区域足够大等等
同人项目 yashchandak/ImageSegmentation https://github.com/yashchandak/ImageSegmentation

**Comment by baidut** [comment]
vitaluha/Road_Detection https://github.com/vitaluha/Road_Detection 
road detection from single image.
                1. Detect edges.
                2. Perform Hough Transform for line detection. 
                      This will detect boundaries of the road.
                3. Perform Flood Fill algorithm in 2 points:
                      left 1/3 of image
                      right 1/3 of image
                4. Remove the unnecesary lines in upper part of image
                   that do not belong to the road.

**Comment by baidut** [comment]
车道线检测程序，采用matlab编写。首先对目标图像进行灰度化处理，然后进行边缘检测，得到车道线的边界。再利用霍夫变换来进行直线匹配，最后从朝向最多的一面选择作为车道线。
http://www.codeforge.cn/article/249958

**Comment by baidut** [comment]
cdessez/road-detection https://github.com/cdessez/road-detection
Qt+opencv开发
项目有配报告，但不是英语，看不懂。采用的是转为俯视图的方式。工程比较简单，值得一看。

**Comment by baidut** [comment]
发现很多项目都是从谷歌仓库的一个拷贝过来的Automatically exported from code.google.com/p/opencv-lane-vehicle-track
值得一看
https://www.youtube.com/watch?v=NG3POm989fU

**Comment by ryanleiwang** [comment]
仅仅在视频上画出车道线，还只是开始。有作出车道线换算成真实世界坐标的开源项目吗？比如换算成车道线距离左右2边车轮各多少米的。

**Comment by baidut** [comment]
这个建议你看一下 Visual SLAM @ryanleiwang
比如 ORB SLAM 是非常好的开源项目 http://webdiis.unizar.es/~raulmur/orbslam/

**Comment by ryanleiwang** [comment]
@baidut  感谢你的建议！
