### ISSUE TITLE
车辆视觉相关数据集汇总

### ISSUE THREAD

**Issue by baidut** [baidut/ITS#59]
**图像**
车辆检测 [TME Motorway dataset](http://cmp.felk.cvut.cz/data/motorway/)
Caltech数据集（经典）[地址](http://vision.caltech.edu/malaa/datasets/caltech-lanes/)

**视频**
**Santaigo Lanes Dataset (SLD2011)** [下载地址](http://ral.ing.puc.cl/datasets/ldw/)
[Santaigo Lanes Dataset (SLD2011) - Lane changing maneuvers at dusk]   [youtube]
(https://www.youtube.com/watch?v=4MSNXvYYR2Y)
Lane tracking with shadows 2 - Bird Eye View - Santaigo Lanes Dataset (SLD2011) [youtube](https://www.youtube.com/watch?v=kHDMUQWIadk)
道路图像理解分割 [Motion-based Segmentation and Recognition Dataset](http://web4.cs.ucl.ac.uk/staff/g.brostow/MotionSegRecData/)

**Comment by tanrye** [comment]
where the data
